server:
  port: 80
  ssl:
    key-store: classpath:tiker.cloud.jks
    key-store-password: ez2g8546fa
    key-store-type: JKS

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tiker?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Zhoujiazheng123...
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.tiker.dao.OrderMapper : debug
    com.tiker.dao.AddressMapper : debug
    com.tiker.dao.UserMapper : debug